### ISSUE TITLE
Error "Cert not yet valid"

### ISSUE THREAD

**Issue by pierre-b** [stephenplusplus/google-auto-auth#1]
Hi @stephenplusplus, today I received the following error in my project using google-auto-auth, and could not figure out how to fix it:

Trace: { [Error: certificate is not yet valid] code: 'CERT_NOT_YET_VALID' }
    at /sites/my-project/api/server.js:229:15
    at /sites/my-project/api/node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/oauth2client.js:239:16
    at /sites/my-project/api/node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/oauth2client.js:205:7
    at /sites/my-project/api/node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/oauth2client.js:185:5
    at Request._callback (/sites/my-project/api/node_modules/google-auto-auth/node_modules/google-auth-library/lib/transporters.js:67:30)
    at self.callback (/sites/my-project/api/node_modules/google-auto-auth/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/sites/my-project/api/node_modules/google-auto-auth/node_modules/google-auth-library/node_modules/request/request.js:861:8)
    at emitOne (events.js:77:13)

Any idea please?

**Comment by stephenplusplus** [comment]
I'm not sure about this one. Could be an issue with the clock on the server running the code? This is an issue with [google-auth-library-nodejs](https://github.com/google/google-auth-library-nodejs). I found https://github.com/google/google-auth-library-nodejs/issues/82 which is not very descriptive, but could be related.

My only suggestions would be googling around for what "CERT_NOT_YET_VALID" means or switching to a JSON key file.

**Comment by pierre-b** [comment]
You were right, the clock of the server was behind... my bad! thanks for the tip
