### ISSUE TITLE
GoogleAuth.JWT() fails

### ISSUE THREAD

**Issue by jomido** [stephenplusplus/google-auto-auth#45]
[This line](https://github.com/stephenplusplus/google-auto-auth/blob/master/index.js#L108) fails with the following error:

```
/node_modules/google-auto-auth/index.js:108
            var authClient = new googleAuthClient.JWT();
                             ^

TypeError: googleAuthClient.JWT is not a constructor
    at fs.readFile (/app/node_modules/google-auto-auth/index.js:108:30)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

I am using `@google-cloud/storage`, which I believe pulls this package in as a dependency. If I roll back to `1.5.2`, then all is well.

Was there more of a change to the `google-auth-library` than anticipated?

One can repro like so:

```
> var GoogleAuth = require('google-auth-library').GoogleAuth;
> var googleAuthClient = new GoogleAuth();
> var authClient = new googleAuthClient.JWT();
TypeError: googleAuthClient.JWT is not a constructor
    at repl:1:18
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:442:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
>
```

**Comment by stephenplusplus** [comment]
Thanks for reporting.

@JustinBeckwith @ofrobots it does look like we need to make a small adjustment to how we instantiate the JWT client. However, even after doing so, I receive an error when trying to use a .p12 file:

```
 Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (internal/crypto/sig.js:85:26)
    at Object.sign (C:\Users\sawch\dev\google-auto-auth\node_modules\jwa\index.js:55:45)
    at Object.jwsSign [as sign] (C:\Users\sawch\dev\google-auto-auth\node_modules\jws\lib\sign-stream.js:23:24)
    at GoogleToken.<anonymous> (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:223:33)
    at step (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:42:23)
    at Object.next (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:23:53)
    at C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:17:71
```

gtoken still supports .p12 files as far as I can tell. Could I be doing something wrong?

```js
const googleAuthLibrary = require('google-auth-library')
const authClient = new googleAuthLibrary.JWT({
  email: 'service-account-email',
  keyFile: 'path/to/key.p12',
  key: 'notasecret'
});
authClient.getAccessToken(console.log)
// error above
```

**Comment by JustinBeckwith** [comment]
Can you share the exact code snippet that reproduces the error?  The call stack you shared doesn't appear to have google-auth-library anywhere in it 0_0.   This should work.

**Comment by stephenplusplus** [comment]
Woops, updated.

**Comment by stephenplusplus** [comment]
Here's a saner one:

```js
const googleAuthLibrary = require('google-auth-library')
const authClient = new googleAuthLibrary.JWT({
  email: 'stephen-windows@nth-circlet-705.iam.gserviceaccount.com',
  keyFile: './key.p12',
  key: 'notasecret'
});
authClient.getAccessToken(console.log)
```
```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (internal/crypto/sig.js:85:26)
    at Object.sign (C:\Users\sawch\dev\google-auto-auth\node_modules\jwa\index.js:55:45)
    at Object.jwsSign [as sign] (C:\Users\sawch\dev\google-auto-auth\node_modules\jws\lib\sign-stream.js:23:24)
    at GoogleToken.<anonymous> (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:223:33)
    at step (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:42:23)
    at Object.next (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:23:53)
    at C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:13:12)
    at GoogleToken.requestToken (C:\Users\sawch\dev\google-auto-auth\node_modules\gtoken\build\src\index.js:209:16)
```

**Comment by JustinBeckwith** [comment]
That call stack still doesn't have google-auth-library in it 😂

**Comment by stephenplusplus** [comment]
Check https://github.com/stephenplusplus/google-auto-auth/issues/45#issuecomment-370584488, as buried as it is, it's in there! A polite DIY request might be required here (please 😄), because it definitely comes through google-auth-library.

**Comment by stephenplusplus** [comment]
I will move this part of the request over to an issue on google-auth-library.

For now, I've got a PR coming to properly instantiate a JWT client, which hopefully will fix the .pem case.

**Comment by JustinBeckwith** [comment]
Ahhh, there we go.  I needed to refresh the page!  Apologies man. Taking a look.

**Comment by JustinBeckwith** [comment]
Oh bother, I see the problem.  You're defining both the `key` AND the `keyFile`.  Key is meant to be the plain text base64 encoded PEM that's embedded in the *.json file.  If you provide a p12 in the keyFile, you don't need to include a key.  gToken is trying to parse `notasecret` as a PEM file :)

Just leave off the `key` and this will work.  I filed https://github.com/google/google-auth-library-nodejs/issues/311 to track giving a better error message here.

**Comment by stephenplusplus** [comment]
D'oh, thank you for that!

@jomido I just released a new patch version of this module, so a fresh un- and re-install should pick up the changes, and hopefully fix the issue. Thanks again for reporting!

**Comment by jomido** [comment]
Awesome work - thanks.
